# Generated by Django 6.0.3 on 2026-03-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['status', '-created_at'], 'verbose_name_plural': 'tasks'},
        ),
    ]
