# Generated by Django 6.0.3 on 2026-03-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': 'tags'},
        ),
    ]
